version: '3'

networks:
  cakephp:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: cake-server
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - cakephp

  mysql:
    image: library/mysql:5.7.22
    container_name: cake-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - cakephp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cake-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - cakephp

#  composer:
#    volumes:
#      - /Users/jpramirez/pdev/cakephp-fixture-factories:/app
#    image: composer:1.9
#    command: ["composer", "install"]
#    container_name: cake-composer
#    depends_on:
#      - php

